variables:
  serviceConnectionToAzure: AzureDevOps
  appName: nodejslinuxsba

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    npm test
  displayName: 'Run Mocha tests'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false

- task: AzureRmWebAppDeployment@4
  inputs:
    azureSubscription: $(serviceConnectionToAzure)
    WebAppName: $(appName)
    Package: '$(System.DefaultWorkingDirectory)'
    GenerateWebConfig: true
    WebConfigParameters: '-Handler iisnode -NodeStartFile server/index.js -appType node'

jobs:
- job: QA
  steps:
  - script: echo hello from QA
- job: Production
  dependsOn: QA
  steps:
  - script: echo hello from Production